version: "3"

services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: santexuser
            POSTGRES_PASSWORD: santexpasswd
            POSTGRES_DB: santexdb
        ports:
            - "3000:3000"
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: santexuser
            POSTGRES_PASSWORD: santexpasswd
            POSTGRES_DB: santexdb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
