version: "3.8"
services:
    db:
        container_name: backend-test-db
        image: postgres:14
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: passwd
            POSTGRES_DB: db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        container_name: backend-test-app
        build: .
        ports:
            - "4001:4001"
        environment:
            DATABASE_URL: postgresql://user:passwd@0.0.0.0:5432/db?schema=public
        depends_on:
            - db
        command: npm run start
        volumes:
            - .:/app
            - /app/node_modules

volumes:
    postgres_data:
